### ISSUE TITLE
Allow A Way To Mutate With Input

### ISSUE THREAD

**Issue by Nilando** [kyren/gc-arena#109]
I'm wondering if it would be possible to give some form of input from outside the arena to a mutation callback. ( I hope I'm not missing a way to do this) I think this should be safe since Gc pointers are scoped to the mutation callback and therefore couldn't be smuggled out via an input type, so unless there's some reason I'm missing it seems fine to give a few options for mutations to take input?

My idea was that maybe there could be a set of mutator traits which a type could then mutate the arena in a few different ways. Heres my quick brainstorm idea...
```
pub trait Mutator<R>
where
    R: for<'a> Rootable<'a>,
{
    type Output;

    fn mutate<'gc>(&self, mu: &'gc Mutation<'gc>, root: &'gc Root<'gc, R>) -> Self::Output;
}

pub trait MutatorMut<R>
where
    R: for<'a> Rootable<'a>,
{
    type Output;

    fn mutate_mut<'gc>(&mut self, _mu: &'gc Mutation<'gc>, _root: &'gc Root<'gc, R>) -> Self::Output;
}

pub trait IntoMutator<R>: Sized
where
    R: for<'a> Rootable<'a>,
{
    type Output;

    fn mutate_into<'gc>(self, _mu: &'gc Mutation<'gc>, _root: &'gc Root<'gc, R>) -> Self::Output;
}

impl<R> Arena<R>
where
    R: for<'a> Rootable<'a>,
{
    #[inline]
    pub fn mutate<M: Mutator<R>>(&self, mutator: &M) -> <M as Mutator<R>>::Output
    {
        unsafe {
            let mc: &'static Mutation<'_> = &*(self.context.mutation_context() as *const _);
            let root: &'static Root<'_, R> = &*(&self.root as *const _);
            mutator.mutate(mc, root)
        }
    }

    #[inline]
    pub fn mutate_mut<M: MutatorMut<R>>(&self, mutator: &mut M) -> <M as MutatorMut<R>>::Output
    {
        unsafe {
            let mc: &'static Mutation<'_> = &*(self.context.mutation_context() as *const _);
            let root: &'static Root<'_, R> = &*(&self.root as *const _);
            mutator.mutate_mut(mc, root)
        }
    }

    #[inline]
    pub fn mutate_into<M: IntoMutator<R>>(&self, mutator: M) -> <M as IntoMutator<R>>::Output
    {
        unsafe {
            let mc: &'static Mutation<'_> = &*(self.context.mutation_context() as *const _);
            let root: &'static Root<'_, R> = &*(&self.root as *const _);
            mutator.mutate_into(mc, root)
        }
    }
```

**Comment by kyren** [comment]
The callbacks we accept in `Arena::mutate` don't have to be `'static` and are `FnOnce`... isn't this exactly the same level of power? You can already pass in input from outside the arena by capturing it in the provided closure as normal. I'm pretty sure if you wanted exactly the interface you're proposing there, you could do it as an extension trait on `Arena` by using the existing `Arena::mutate` method.

Maybe I'm missing something?

**Comment by Nilando** [comment]
Nope your right my mistake! Silly me forgot that closures are a thing.
