### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by dragazo** [kyren/gc-arena#42]
Is there any projected timeline for getting a new release on crates.io? In particular, some of the recent features like #23 and #32 would be very useful to have in the published version for some projects I've been working on (using git dep for the time being, but that makes them unpublishable). But I realize there's still some active work going on, including some soundness fixes, so I don't mean to rush anything if it's not ready.

**Comment by kyren** [comment]
This crate desperately needs another release, the version on crates.io is... at this point *very* behind.

**Comment by dragazo** [comment]
Just throwing this out there since I saw some of the recent commits are breaking changes: crates.io also supports alpha releases. So there could be like a `0.3.0-alpha.0` release if you want a new published version but don't want to commit to anything quite yet. Alpha releases don't get used by fuzzy versioning, so (afaik) it can't break existing code even if they did `gc-arena = "*"`.
