### ISSUE TITLE
Compiling to WebAssembly

### ISSUE THREAD

**Issue by erlend-sh** [kyren/gc-arena#69]
Is WASM-support within the longer term scope of this project?

It would make piccolo usable by WASM-scriptable game platforms such as [Ambient](https://www.ambient.run) and [Gamercade](https://gamercade.io/).

https://github.com/WebAssembly/gc/blob/main/proposals/gc/MVP.md
https://github.com/dart-lang/sdk/blob/main/pkg/dart2wasm/README.md

**Comment by kyren** [comment]
Oh.... also I'm very very stupid, this is already used by Ruffle which specifically targets wasm32. It *definitely* already works in wasm.

**Comment by dragazo** [comment]
Yeah, I've definitely used this in a wasm project before, but that was an older version (the crates.io published version). I think the only change that might be good is adding wasm as a CI target to make sure it never breaks wasm support. But I'm sure Ruffle would (eventually) complain if they upgrade the dep and it stops working.

**Comment by kyren** [comment]
Closing, since this has been supported since forever.
