### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by Aaron1011** [kyren/gc-arena#8]
PR #6 would be useful to use in [Ruffle](https://github.com/ruffle-rs/ruffle). Could you make a new minor release?

**Comment by kyren** [comment]
Ass soon as #9 is resolved I will make a new release.

**Comment by Aaron1011** [comment]
@kyren: Now that https://github.com/kyren/gc-arena/pull/9 has been merged, is there anything blocking the release?

**Comment by kyren** [comment]
> @kyren: Now that #9 has been merged, is there anything blocking the release?

No, just laziness on my part, I will do this today, sorry for the delay!

**Comment by kyren** [comment]
Finally done.. very very late :frowning_face:
