### ISSUE TITLE
How do I store a reference to a static lifetimed reference inside a GC'ed value? 

### ISSUE THREAD

**Issue by glyh** [kyren/gc-arena#99]
My use case is basically storing a constant `&str` inside a GC'ed tagged enum(which is also recursive).

I've read through the example but I didn't find something like this. I would appreciate it if you can provide some examples, thank you!

**Comment by glyh** [comment]
For now attempting this directly with rust lifetime params I got a "lifetime should be at least as long as 'static" error.

**Comment by kyren** [comment]
Generally you can't mix other non-'static lifetimes than 'gc into gc-arena, but it sorta depends. Am I understanding things correctly that you want to keep around a `&'a &'static str` or a `&'a mut &'static str`, and not just a `&'static str`?

**Comment by glyh** [comment]
I want to keep around a `'static` inside a `'gc`

**Comment by kyren** [comment]
You can keep around a `&'static T` inside the arena, there is no need for `RefCell` at all, are you maybe missing a `#[collect(require_static)]` on the field?

**Comment by glyh** [comment]
This might be the way to go, I'll take a look at this. Thank you!

**Comment by kyren** [comment]
Ah, I may have told you incorrectly if you didn't see my edit, I'm sorry!

If you can't figure it out, feel free to follow up. If you can show me what error you're seeing and a code example I can help.
